from types import SimpleNamespace
from unittest.mock import Mock

import pytest

from app.services.retrieval_service import RetrievalError, RetrievalService


def test_retrieve_returns_structured_top_k_chunks():
    embedding_service = Mock()
    embedding_service.embed_text.return_value = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

    db = Mock()
    db.scalars.return_value.all.return_value = [
        SimpleNamespace(
            content="Conteudo A",
            document=SimpleNamespace(
                title="Documento A",
                document_type="regulation",
                version="2026",
            ),
            page_number=10,
            chunk_index=3,
            document_id=1,
        ),
        SimpleNamespace(
            content="Conteudo B",
            document=SimpleNamespace(
                title="Documento B",
                document_type="norm",
                version="1.0",
            ),
            page_number=12,
            chunk_index=4,
            document_id=2,
        ),
    ]

    service = RetrievalService(db=db, embedding_service=embedding_service)
    result = service.retrieve("Qual a largura minima?", top_k=2)

    assert len(result) == 2
    assert result[0]["content"] == "Conteudo A"
    assert result[0]["document_title"] == "Documento A"
    assert result[0]["document_type"] == "regulation"
    assert result[0]["version"] == "2026"
    assert result[0]["page_number"] == 10
    assert result[0]["chunk_index"] == 3
    assert result[0]["document_id"] == 1


def test_retrieve_rejects_invalid_top_k():
    service = RetrievalService(db=Mock(), embedding_service=Mock())

    with pytest.raises(ValueError):
        service.retrieve("Pergunta valida", top_k=0)


def test_retrieve_wraps_embedding_errors():
    embedding_service = Mock()
    embedding_service.embed_text.side_effect = ValueError("empty")

    service = RetrievalService(db=Mock(), embedding_service=embedding_service)

    with pytest.raises(RetrievalError, match="embed question"):
        service.retrieve("Pergunta", top_k=3)


def test_retrieve_wraps_database_errors():
    embedding_service = Mock()
    embedding_service.embed_text.return_value = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

    db = Mock()
    db.scalars.side_effect = RuntimeError("db unavailable")

    service = RetrievalService(db=db, embedding_service=embedding_service)

    with pytest.raises(RetrievalError, match="vector store"):
        service.retrieve("Pergunta", top_k=3)


def test_retrieve_rejects_embedding_dimension_mismatch():
    embedding_service = Mock()
    embedding_service.embed_text.return_value = [0.1, 0.2, 0.3]

    service = RetrievalService(db=Mock(), embedding_service=embedding_service)

    with pytest.raises(RetrievalError, match="dimension mismatch"):
        service.retrieve("Pergunta", top_k=3)


def test_retrieve_applies_optional_filters_to_query():
    embedding_service = Mock()
    embedding_service.embed_text.return_value = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

    db = Mock()
    db.scalars.return_value.all.return_value = []

    service = RetrievalService(db=db, embedding_service=embedding_service)
    service.retrieve(
        "Pergunta",
        top_k=3,
        filters={"document_id": 7, "document_type": "fire_regulation", "version": "2026"},
    )

    stmt = db.scalars.call_args.args[0]
    stmt_text = str(stmt)
    assert "chunks.document_id" in stmt_text
    assert "EXISTS" in stmt_text  # generated by relationship `.has(...)` filters
